include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**, app/**.g.dart, lib/**.g.dart]

# https://dart.dev/tools/analysis
# https://dart.dev/tools/linter-rules/all
linter:
  rules:
    prefer_single_quotes: true
