name: dart_scan
description: dart_scan project
version: 2025.504.1204
homepage: 
repository: https://github.com/dart-pkg/dart_scan
environment:
  sdk: ^3.7.2
dependencies:
  pubspec_parse: ^1.5.0
  sys: ^2025.504.1149
dev_dependencies:
  debug_output: ^2025.502.2007
  lints: ^5.1.1
  path: ^1.9.1
  test: ^1.25.15
