name: "dart_scan"
description: "dart_scan project"
version: 2025.424.1203
homepage: null
repository: "https://github.com/dart-pkg/dart_scan"
environment:
  sdk: "^3.7.2"
dependencies:
  sys: ^2025.424.246
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  path: ^1.9.1
  test: ^1.25.15
