name: dart_scan
description: "dart_scan package project"
version: 0.0.2
homepage:
repository: https://github.com/dart-pkg/dart_scan

environment:
  sdk: ^3.7.2

dependencies:
  output: ^1.0.1
  path: ^1.9.1
  sys: ^0.0.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
