name: "dart_scan"
description: "dart_scan project"
version: "2025.421.2226"
homepage: null
repository: "https://github.com/dart-pkg/dart_scan"
environment:
  sdk: "^3.7.2"
dependencies:
  sys: ^2025.421.2149
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.6
  path: ^1.9.1
  test: ^1.25.15
