name: "dart_scan"
description: "dart_scan project"
version: 2025.427.1709
homepage: null
repository: "https://github.com/dart-pkg/dart_scan"
environment:
  sdk: "^3.7.2"
dependencies:
  sys: ^2025.426.2256
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.426.2027
  path: ^1.9.1
  test: ^1.25.15
